/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAllRouteImport } from './routes/_authenticated.all'
import { Route as AuthenticatedDmRouteImport } from './routes/_authenticated.dm'
import { Route as AuthenticatedMailboxesRouteImport } from './routes/_authenticated.mailboxes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AuthenticatedDmIdRouteImport } from './routes/_authenticated.dm.$id'
import { Route as AuthenticatedMIdRouteImport } from './routes/_authenticated.m.$id'
import { Route as AuthenticatedMsgIdRouteImport } from './routes/_authenticated.msg.$id'
import { Route as ApiPublicInboundRouteImport } from './routes/api/public/inbound'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllRoute = AuthenticatedAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDmRoute = AuthenticatedDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailboxesRoute = AuthenticatedMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDmIdRoute = AuthenticatedDmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDmRoute,
} as any)
const AuthenticatedMIdRoute = AuthenticatedMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMsgIdRoute = AuthenticatedMsgIdRouteImport.update({
  id: '/msg/$id',
  path: '/msg/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicInboundRoute = ApiPublicInboundRouteImport.update({
  id: '/api/public/inbound',
  path: '/api/public/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/all': typeof AuthenticatedAllRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/dm/$id': typeof AuthenticatedDmIdRoute
  '/m/$id': typeof AuthenticatedMIdRoute
  '/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/all': typeof AuthenticatedAllRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/dm/$id': typeof AuthenticatedDmIdRoute
  '/m/$id': typeof AuthenticatedMIdRoute
  '/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/all': typeof AuthenticatedAllRoute
  '/_authenticated/dm': typeof AuthenticatedDmRouteWithChildren
  '/_authenticated/mailboxes': typeof AuthenticatedMailboxesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/_authenticated/dm/$id': typeof AuthenticatedDmIdRoute
  '/_authenticated/m/$id': typeof AuthenticatedMIdRoute
  '/_authenticated/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/all'
    | '/dm'
    | '/mailboxes'
    | '/settings'
    | '/api/healthz'
    | '/dm/$id'
    | '/m/$id'
    | '/msg/$id'
    | '/api/public/inbound'
    | '/api/public/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/all'
    | '/dm'
    | '/mailboxes'
    | '/settings'
    | '/api/healthz'
    | '/dm/$id'
    | '/m/$id'
    | '/msg/$id'
    | '/api/public/inbound'
    | '/api/public/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/all'
    | '/_authenticated/dm'
    | '/_authenticated/mailboxes'
    | '/_authenticated/settings'
    | '/api/healthz'
    | '/_authenticated/dm/$id'
    | '/_authenticated/m/$id'
    | '/_authenticated/msg/$id'
    | '/api/public/inbound'
    | '/api/public/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiPublicInboundRoute: typeof ApiPublicInboundRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/all': {
      id: '/_authenticated/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AuthenticatedAllRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dm': {
      id: '/_authenticated/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AuthenticatedDmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mailboxes': {
      id: '/_authenticated/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AuthenticatedMailboxesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dm/$id': {
      id: '/_authenticated/dm/$id'
      path: '/$id'
      fullPath: '/dm/$id'
      preLoaderRoute: typeof AuthenticatedDmIdRouteImport
      parentRoute: typeof AuthenticatedDmRoute
    }
    '/_authenticated/m/$id': {
      id: '/_authenticated/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof AuthenticatedMIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/msg/$id': {
      id: '/_authenticated/msg/$id'
      path: '/msg/$id'
      fullPath: '/msg/$id'
      preLoaderRoute: typeof AuthenticatedMsgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/inbound': {
      id: '/api/public/inbound'
      path: '/api/public/inbound'
      fullPath: '/api/public/inbound'
      preLoaderRoute: typeof ApiPublicInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDmRouteChildren {
  AuthenticatedDmIdRoute: typeof AuthenticatedDmIdRoute
}

const AuthenticatedDmRouteChildren: AuthenticatedDmRouteChildren = {
  AuthenticatedDmIdRoute: AuthenticatedDmIdRoute,
}

const AuthenticatedDmRouteWithChildren = AuthenticatedDmRoute._addFileChildren(
  AuthenticatedDmRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAllRoute: typeof AuthenticatedAllRoute
  AuthenticatedDmRoute: typeof AuthenticatedDmRouteWithChildren
  AuthenticatedMailboxesRoute: typeof AuthenticatedMailboxesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMIdRoute: typeof AuthenticatedMIdRoute
  AuthenticatedMsgIdRoute: typeof AuthenticatedMsgIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAllRoute: AuthenticatedAllRoute,
  AuthenticatedDmRoute: AuthenticatedDmRouteWithChildren,
  AuthenticatedMailboxesRoute: AuthenticatedMailboxesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMIdRoute: AuthenticatedMIdRoute,
  AuthenticatedMsgIdRoute: AuthenticatedMsgIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiPublicInboundRoute: ApiPublicInboundRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
