/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedMailboxesRouteImport } from './routes/_authenticated.mailboxes'
import { Route as AuthenticatedDmRouteImport } from './routes/_authenticated.dm'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated.compose'
import { Route as AuthenticatedApiAccessRouteImport } from './routes/_authenticated.api-access'
import { Route as AuthenticatedAllRouteImport } from './routes/_authenticated.all'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDmIndexRouteImport } from './routes/_authenticated.dm.index'
import { Route as ApiV1MailboxesRouteImport } from './routes/api/v1/mailboxes'
import { Route as ApiV1LogsRouteImport } from './routes/api/v1/logs'
import { Route as ApiV1DomainsRouteImport } from './routes/api/v1/domains'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'
import { Route as ApiPublicInboundRouteImport } from './routes/api/public/inbound'
import { Route as ApiPublicGuestSessionRouteImport } from './routes/api/public/guest-session'
import { Route as ApiPublicGuestRouteImport } from './routes/api/public/guest'
import { Route as ApiInternalOutboundHealthRouteImport } from './routes/api/internal/outbound-health'
import { Route as AuthenticatedMsgIdRouteImport } from './routes/_authenticated.msg.$id'
import { Route as AuthenticatedMIdRouteImport } from './routes/_authenticated.m.$id'
import { Route as AuthenticatedDmIdRouteImport } from './routes/_authenticated.dm.$id'
import { Route as ApiV1MailboxesIdRouteImport } from './routes/api/v1/mailboxes.$id'
import { Route as ApiV1MailboxesIdMessagesRouteImport } from './routes/api/v1/mailboxes.$id.messages'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailboxesRoute = AuthenticatedMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDmRoute = AuthenticatedDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiAccessRoute = AuthenticatedApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllRoute = AuthenticatedAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDmIndexRoute = AuthenticatedDmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDmRoute,
} as any)
const ApiV1MailboxesRoute = ApiV1MailboxesRouteImport.update({
  id: '/api/v1/mailboxes',
  path: '/api/v1/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LogsRoute = ApiV1LogsRouteImport.update({
  id: '/api/v1/logs',
  path: '/api/v1/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DomainsRoute = ApiV1DomainsRouteImport.update({
  id: '/api/v1/domains',
  path: '/api/v1/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundRoute = ApiPublicInboundRouteImport.update({
  id: '/api/public/inbound',
  path: '/api/public/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestSessionRoute = ApiPublicGuestSessionRouteImport.update({
  id: '/api/public/guest-session',
  path: '/api/public/guest-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestRoute = ApiPublicGuestRouteImport.update({
  id: '/api/public/guest',
  path: '/api/public/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalOutboundHealthRoute =
  ApiInternalOutboundHealthRouteImport.update({
    id: '/api/internal/outbound-health',
    path: '/api/internal/outbound-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMsgIdRoute = AuthenticatedMsgIdRouteImport.update({
  id: '/msg/$id',
  path: '/msg/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMIdRoute = AuthenticatedMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDmIdRoute = AuthenticatedDmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDmRoute,
} as any)
const ApiV1MailboxesIdRoute = ApiV1MailboxesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1MailboxesRoute,
} as any)
const ApiV1MailboxesIdMessagesRoute =
  ApiV1MailboxesIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiV1MailboxesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/all': typeof AuthenticatedAllRoute
  '/api-access': typeof AuthenticatedApiAccessRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/dm/$id': typeof AuthenticatedDmIdRoute
  '/m/$id': typeof AuthenticatedMIdRoute
  '/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/internal/outbound-health': typeof ApiInternalOutboundHealthRoute
  '/api/public/guest': typeof ApiPublicGuestRoute
  '/api/public/guest-session': typeof ApiPublicGuestSessionRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/v1/domains': typeof ApiV1DomainsRoute
  '/api/v1/logs': typeof ApiV1LogsRoute
  '/api/v1/mailboxes': typeof ApiV1MailboxesRouteWithChildren
  '/dm/': typeof AuthenticatedDmIndexRoute
  '/api/v1/mailboxes/$id': typeof ApiV1MailboxesIdRouteWithChildren
  '/api/v1/mailboxes/$id/messages': typeof ApiV1MailboxesIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/all': typeof AuthenticatedAllRoute
  '/api-access': typeof AuthenticatedApiAccessRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/dm/$id': typeof AuthenticatedDmIdRoute
  '/m/$id': typeof AuthenticatedMIdRoute
  '/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/internal/outbound-health': typeof ApiInternalOutboundHealthRoute
  '/api/public/guest': typeof ApiPublicGuestRoute
  '/api/public/guest-session': typeof ApiPublicGuestSessionRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/v1/domains': typeof ApiV1DomainsRoute
  '/api/v1/logs': typeof ApiV1LogsRoute
  '/api/v1/mailboxes': typeof ApiV1MailboxesRouteWithChildren
  '/dm': typeof AuthenticatedDmIndexRoute
  '/api/v1/mailboxes/$id': typeof ApiV1MailboxesIdRouteWithChildren
  '/api/v1/mailboxes/$id/messages': typeof ApiV1MailboxesIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/all': typeof AuthenticatedAllRoute
  '/_authenticated/api-access': typeof AuthenticatedApiAccessRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/dm': typeof AuthenticatedDmRouteWithChildren
  '/_authenticated/mailboxes': typeof AuthenticatedMailboxesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/_authenticated/dm/$id': typeof AuthenticatedDmIdRoute
  '/_authenticated/m/$id': typeof AuthenticatedMIdRoute
  '/_authenticated/msg/$id': typeof AuthenticatedMsgIdRoute
  '/api/internal/outbound-health': typeof ApiInternalOutboundHealthRoute
  '/api/public/guest': typeof ApiPublicGuestRoute
  '/api/public/guest-session': typeof ApiPublicGuestSessionRoute
  '/api/public/inbound': typeof ApiPublicInboundRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/v1/domains': typeof ApiV1DomainsRoute
  '/api/v1/logs': typeof ApiV1LogsRoute
  '/api/v1/mailboxes': typeof ApiV1MailboxesRouteWithChildren
  '/_authenticated/dm/': typeof AuthenticatedDmIndexRoute
  '/api/v1/mailboxes/$id': typeof ApiV1MailboxesIdRouteWithChildren
  '/api/v1/mailboxes/$id/messages': typeof ApiV1MailboxesIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/all'
    | '/api-access'
    | '/compose'
    | '/dm'
    | '/mailboxes'
    | '/settings'
    | '/api/healthz'
    | '/dm/$id'
    | '/m/$id'
    | '/msg/$id'
    | '/api/internal/outbound-health'
    | '/api/public/guest'
    | '/api/public/guest-session'
    | '/api/public/inbound'
    | '/api/public/register'
    | '/api/v1/domains'
    | '/api/v1/logs'
    | '/api/v1/mailboxes'
    | '/dm/'
    | '/api/v1/mailboxes/$id'
    | '/api/v1/mailboxes/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/all'
    | '/api-access'
    | '/compose'
    | '/mailboxes'
    | '/settings'
    | '/api/healthz'
    | '/dm/$id'
    | '/m/$id'
    | '/msg/$id'
    | '/api/internal/outbound-health'
    | '/api/public/guest'
    | '/api/public/guest-session'
    | '/api/public/inbound'
    | '/api/public/register'
    | '/api/v1/domains'
    | '/api/v1/logs'
    | '/api/v1/mailboxes'
    | '/dm'
    | '/api/v1/mailboxes/$id'
    | '/api/v1/mailboxes/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/all'
    | '/_authenticated/api-access'
    | '/_authenticated/compose'
    | '/_authenticated/dm'
    | '/_authenticated/mailboxes'
    | '/_authenticated/settings'
    | '/api/healthz'
    | '/_authenticated/dm/$id'
    | '/_authenticated/m/$id'
    | '/_authenticated/msg/$id'
    | '/api/internal/outbound-health'
    | '/api/public/guest'
    | '/api/public/guest-session'
    | '/api/public/inbound'
    | '/api/public/register'
    | '/api/v1/domains'
    | '/api/v1/logs'
    | '/api/v1/mailboxes'
    | '/_authenticated/dm/'
    | '/api/v1/mailboxes/$id'
    | '/api/v1/mailboxes/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiInternalOutboundHealthRoute: typeof ApiInternalOutboundHealthRoute
  ApiPublicGuestRoute: typeof ApiPublicGuestRoute
  ApiPublicGuestSessionRoute: typeof ApiPublicGuestSessionRoute
  ApiPublicInboundRoute: typeof ApiPublicInboundRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiV1DomainsRoute: typeof ApiV1DomainsRoute
  ApiV1LogsRoute: typeof ApiV1LogsRoute
  ApiV1MailboxesRoute: typeof ApiV1MailboxesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mailboxes': {
      id: '/_authenticated/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AuthenticatedMailboxesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dm': {
      id: '/_authenticated/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AuthenticatedDmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-access': {
      id: '/_authenticated/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof AuthenticatedApiAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/all': {
      id: '/_authenticated/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AuthenticatedAllRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dm/': {
      id: '/_authenticated/dm/'
      path: '/'
      fullPath: '/dm/'
      preLoaderRoute: typeof AuthenticatedDmIndexRouteImport
      parentRoute: typeof AuthenticatedDmRoute
    }
    '/api/v1/mailboxes': {
      id: '/api/v1/mailboxes'
      path: '/api/v1/mailboxes'
      fullPath: '/api/v1/mailboxes'
      preLoaderRoute: typeof ApiV1MailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/logs': {
      id: '/api/v1/logs'
      path: '/api/v1/logs'
      fullPath: '/api/v1/logs'
      preLoaderRoute: typeof ApiV1LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/domains': {
      id: '/api/v1/domains'
      path: '/api/v1/domains'
      fullPath: '/api/v1/domains'
      preLoaderRoute: typeof ApiV1DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound': {
      id: '/api/public/inbound'
      path: '/api/public/inbound'
      fullPath: '/api/public/inbound'
      preLoaderRoute: typeof ApiPublicInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-session': {
      id: '/api/public/guest-session'
      path: '/api/public/guest-session'
      fullPath: '/api/public/guest-session'
      preLoaderRoute: typeof ApiPublicGuestSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest': {
      id: '/api/public/guest'
      path: '/api/public/guest'
      fullPath: '/api/public/guest'
      preLoaderRoute: typeof ApiPublicGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/outbound-health': {
      id: '/api/internal/outbound-health'
      path: '/api/internal/outbound-health'
      fullPath: '/api/internal/outbound-health'
      preLoaderRoute: typeof ApiInternalOutboundHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/msg/$id': {
      id: '/_authenticated/msg/$id'
      path: '/msg/$id'
      fullPath: '/msg/$id'
      preLoaderRoute: typeof AuthenticatedMsgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/m/$id': {
      id: '/_authenticated/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof AuthenticatedMIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dm/$id': {
      id: '/_authenticated/dm/$id'
      path: '/$id'
      fullPath: '/dm/$id'
      preLoaderRoute: typeof AuthenticatedDmIdRouteImport
      parentRoute: typeof AuthenticatedDmRoute
    }
    '/api/v1/mailboxes/$id': {
      id: '/api/v1/mailboxes/$id'
      path: '/$id'
      fullPath: '/api/v1/mailboxes/$id'
      preLoaderRoute: typeof ApiV1MailboxesIdRouteImport
      parentRoute: typeof ApiV1MailboxesRoute
    }
    '/api/v1/mailboxes/$id/messages': {
      id: '/api/v1/mailboxes/$id/messages'
      path: '/messages'
      fullPath: '/api/v1/mailboxes/$id/messages'
      preLoaderRoute: typeof ApiV1MailboxesIdMessagesRouteImport
      parentRoute: typeof ApiV1MailboxesIdRoute
    }
  }
}

interface AuthenticatedDmRouteChildren {
  AuthenticatedDmIdRoute: typeof AuthenticatedDmIdRoute
  AuthenticatedDmIndexRoute: typeof AuthenticatedDmIndexRoute
}

const AuthenticatedDmRouteChildren: AuthenticatedDmRouteChildren = {
  AuthenticatedDmIdRoute: AuthenticatedDmIdRoute,
  AuthenticatedDmIndexRoute: AuthenticatedDmIndexRoute,
}

const AuthenticatedDmRouteWithChildren = AuthenticatedDmRoute._addFileChildren(
  AuthenticatedDmRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAllRoute: typeof AuthenticatedAllRoute
  AuthenticatedApiAccessRoute: typeof AuthenticatedApiAccessRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedDmRoute: typeof AuthenticatedDmRouteWithChildren
  AuthenticatedMailboxesRoute: typeof AuthenticatedMailboxesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMIdRoute: typeof AuthenticatedMIdRoute
  AuthenticatedMsgIdRoute: typeof AuthenticatedMsgIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAllRoute: AuthenticatedAllRoute,
  AuthenticatedApiAccessRoute: AuthenticatedApiAccessRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedDmRoute: AuthenticatedDmRouteWithChildren,
  AuthenticatedMailboxesRoute: AuthenticatedMailboxesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMIdRoute: AuthenticatedMIdRoute,
  AuthenticatedMsgIdRoute: AuthenticatedMsgIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiV1MailboxesIdRouteChildren {
  ApiV1MailboxesIdMessagesRoute: typeof ApiV1MailboxesIdMessagesRoute
}

const ApiV1MailboxesIdRouteChildren: ApiV1MailboxesIdRouteChildren = {
  ApiV1MailboxesIdMessagesRoute: ApiV1MailboxesIdMessagesRoute,
}

const ApiV1MailboxesIdRouteWithChildren =
  ApiV1MailboxesIdRoute._addFileChildren(ApiV1MailboxesIdRouteChildren)

interface ApiV1MailboxesRouteChildren {
  ApiV1MailboxesIdRoute: typeof ApiV1MailboxesIdRouteWithChildren
}

const ApiV1MailboxesRouteChildren: ApiV1MailboxesRouteChildren = {
  ApiV1MailboxesIdRoute: ApiV1MailboxesIdRouteWithChildren,
}

const ApiV1MailboxesRouteWithChildren = ApiV1MailboxesRoute._addFileChildren(
  ApiV1MailboxesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiInternalOutboundHealthRoute: ApiInternalOutboundHealthRoute,
  ApiPublicGuestRoute: ApiPublicGuestRoute,
  ApiPublicGuestSessionRoute: ApiPublicGuestSessionRoute,
  ApiPublicInboundRoute: ApiPublicInboundRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
  ApiV1DomainsRoute: ApiV1DomainsRoute,
  ApiV1LogsRoute: ApiV1LogsRoute,
  ApiV1MailboxesRoute: ApiV1MailboxesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
